/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RecipesRouteImport } from './routes/recipes'
import { Route as MealPlanRouteImport } from './routes/meal-plan'
import { Route as CreateRouteImport } from './routes/create'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecipeRecipeIdRouteImport } from './routes/recipe.$recipeId'
import { Route as ListListIdRouteImport } from './routes/list.$listId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRoute = RecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const MealPlanRoute = MealPlanRouteImport.update({
  id: '/meal-plan',
  path: '/meal-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipeRecipeIdRoute = RecipeRecipeIdRouteImport.update({
  id: '/recipe/$recipeId',
  path: '/recipe/$recipeId',
  getParentRoute: () => rootRouteImport,
} as any)
const ListListIdRoute = ListListIdRouteImport.update({
  id: '/list/$listId',
  path: '/list/$listId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/meal-plan': typeof MealPlanRoute
  '/recipes': typeof RecipesRoute
  '/settings': typeof SettingsRoute
  '/list/$listId': typeof ListListIdRoute
  '/recipe/$recipeId': typeof RecipeRecipeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/meal-plan': typeof MealPlanRoute
  '/recipes': typeof RecipesRoute
  '/settings': typeof SettingsRoute
  '/list/$listId': typeof ListListIdRoute
  '/recipe/$recipeId': typeof RecipeRecipeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/meal-plan': typeof MealPlanRoute
  '/recipes': typeof RecipesRoute
  '/settings': typeof SettingsRoute
  '/list/$listId': typeof ListListIdRoute
  '/recipe/$recipeId': typeof RecipeRecipeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/meal-plan'
    | '/recipes'
    | '/settings'
    | '/list/$listId'
    | '/recipe/$recipeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/meal-plan'
    | '/recipes'
    | '/settings'
    | '/list/$listId'
    | '/recipe/$recipeId'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/meal-plan'
    | '/recipes'
    | '/settings'
    | '/list/$listId'
    | '/recipe/$recipeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  MealPlanRoute: typeof MealPlanRoute
  RecipesRoute: typeof RecipesRoute
  SettingsRoute: typeof SettingsRoute
  ListListIdRoute: typeof ListListIdRoute
  RecipeRecipeIdRoute: typeof RecipeRecipeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes': {
      id: '/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meal-plan': {
      id: '/meal-plan'
      path: '/meal-plan'
      fullPath: '/meal-plan'
      preLoaderRoute: typeof MealPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipe/$recipeId': {
      id: '/recipe/$recipeId'
      path: '/recipe/$recipeId'
      fullPath: '/recipe/$recipeId'
      preLoaderRoute: typeof RecipeRecipeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list/$listId': {
      id: '/list/$listId'
      path: '/list/$listId'
      fullPath: '/list/$listId'
      preLoaderRoute: typeof ListListIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  MealPlanRoute: MealPlanRoute,
  RecipesRoute: RecipesRoute,
  SettingsRoute: SettingsRoute,
  ListListIdRoute: ListListIdRoute,
  RecipeRecipeIdRoute: RecipeRecipeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
